/* ==============
    EXERCISE LIST
 ================ */
const exercises = [
  // QUADRICEPS
  {
    name: "Leg press",
    muscleGroup: "thigh",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
  {
    name: "Squat",
    muscleGroup: "thigh",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
  {
    name: "Seated knee extension",
    muscleGroup: "thigh",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
  // HAMSTRING
  {
    name: "Deadlift",
    muscleGroup: "hamstring",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
  {
    name: "Hamstring curl",
    muscleGroup: "hamstring",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
  // CALVES
  {
    name: "Standing calf raise",
    muscleGroup: "calf",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
  {
    name: "Seated calf raise",
    muscleGroup: "calf",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
  // CHEST
  {
    name: "Bench press",
    muscleGroup: "chest",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
  {
    name: "Dips",
    muscleGroup: "chest",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
  // BACK
  {
    name: "Machine rows",
    muscleGroup: "back",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
  {
    name: "Pull up machine",
    muscleGroup: "back",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
  //SHOULDERS
  {
    name: "Lateral raise",
    muscleGroup: "shoulders",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
  {
    name: "Shrugs",
    muscleGroup: "shoulders",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
    color: "#43aa8b",
  },
  //CORE
  {
    name: "Leg lifts",
    muscleGroup: "core",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
  {
    name: "Crunches",
    muscleGroup: "core",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
  {
    name: "Twists",
    muscleGroup: "core",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
  //BICEPS
  {
    name: "Bicep curls",
    muscleGroup: "biceps",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
  {
    name: "Concentration curls",
    muscleGroup: "biceps",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
  //TRICEPS
  {
    name: "Cable pulldown",
    muscleGroup: "triceps",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
  {
    name: "Tricep overhead extension",
    muscleGroup: "triceps",
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: "",
  },
];
/* 
Images needed for:
Calf raise
Seated calf raise
Leg lifts
*/

export default exercises;